QMS.Presentation/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QMS.Presentation.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

QMS.Presentation/Controllers/QMSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QMS.Repo;
using QMS.ViewModel;

namespace QMS.Presentation.Controllers
{
    public class QMSController : Controller
    {
        // GET: QMS
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            return PartialView("_List", QHeadRepo.All());
        }

        public ActionResult Create()
        {
            return PartialView("_Create", QHeadRepo.GetQHeadCode());
        }
        [HttpPost]
        public ActionResult Create(QHeadViewModel model)
        {
            ResponResultViewModel result = QHeadRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(int id)
        {
            return PartialView("_Edit", QHeadRepo.GetQuestion(id));
        }
        [HttpPost]
        public ActionResult Edit(QHeadViewModel model)
        {
            ResponResultViewModel respon = QHeadRepo.Update(model);

            return Json(new
            {
                success = respon.Success,
                message = respon.Message,
                entity = respon.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult EditQue(int id)
        {
            return PartialView("_QuestionEdit", QHeadRepo.GetQuestionDetail(id));
        }

        [HttpPost]
        public ActionResult EditQue(QDetailViewModel model)
        {
            ResponResultViewModel respon = QHeadRepo.EditQue(model);
            return Json(new
            {
                success = respon.Success,
                message = respon.Message,
                entity = respon.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Detail(int id)
        {
            return PartialView("_Detail", QHeadRepo.Detail(id));
        }

        public ActionResult Detailitem(QDetailViewModel model)
        {
            return PartialView("_Detailitem", QHeadRepo.DetailItem(model));
        }

        public ActionResult Question()
        {
            return PartialView("_Question");
        }


    }
}

QMS.Presentation/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

QMS.Presentation/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

QMS.Presentation/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

QMS.Presentation/Views/QMS/Index.cshtml
@{
    ViewBag.Title = "Question Management";
}
<div class="panel panel-body">
    <div class="table-list">
        Hi halo
    </div>
</div>

@* Modal *@
<div id="mver" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #ffad5b">
                <button id="bmodver" type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 id="mvertitle" class="modal-title">Create</h4>
            </div>
            <div id="mverbody" class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="qmod" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #ffad5b">
                <button id="bmodque" type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 id="qmodtitle" class="modal-title">Create</h4>
            </div>
            <div id="qmodbody" class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->





@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            GetList();
        });

        function GetList(){
            $.ajax({
                url: '@Url.Action("List","QMS")',
                type: 'get',
                success: function (result) {
                    $(".table-list").html(result);
                },
                error: function (err) {
                    $(".table-list").html(err);
                }
            });
        }
    </script>

}

QMS.Presentation/Views/QMS/_Create.cshtml
@model QMS.ViewModel.QHeadViewModel


@using (Html.BeginForm("Create", "QMS", FormMethod.Post, new { id = "create-form", name = "create-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.HiddenFor(model => model.q_id)
        <div class="form-group">
            @Html.LabelFor(model => model.q_code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.q_code, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                @Html.ValidationMessageFor(model => model.q_code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.q_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.q_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.q_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.q_type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    List<SelectListItem> listItems = new List<SelectListItem>();
                    listItems.Add(new SelectListItem
                    {
                        Text = "Personality",
                        Value = "Personality"
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "Technical",
                        Value = "Technical"
                    });
                }
                @Html.DropDownListFor(model => model.q_type, listItems, "-- Type --", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.q_type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Close" class="btn btn-default" data-dismiss="modal" />
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script type="text/javascript">
        $("#create-form").submit(function () {
            $.ajax({
                url: '@Url.Action("Create","QMS")',
                type: 'post',
                data: $(this).serialize(),
                success: function (result) {
                    if (result.success) {
                        alert("Data Successfully Added");
                        $("#mver").modal("hide");
                        GetList();
                    } else {
                        alert("Error!." + result.message)
                    }
                }
            });
            return false;
        });

</script>

QMS.Presentation/Views/QMS/_Detail.cshtml
@model IEnumerable<QMS.ViewModel.QDetailViewModel>

<table class="table">
    <thead>
        <tr class="row">
            <td class="col-sm-2">
                @Html.DisplayNameFor(model => model.q_no)
            </td>
            <td class="col-sm-6">
                @Html.DisplayNameFor(model => model.q_question)
            </td>
            <td class="col-sm-4">
                #
            </td>
        </tr>

    </thead>

    <tbody id="question-list">
        @foreach (var item in Model)
        {
            @Html.Partial("_Detailitem", item)
        }
    </tbody>

</table>

QMS.Presentation/Views/QMS/_DetailItem.cshtml
@model QMS.ViewModel.QDetailViewModel

<tr class="row">
    <td class="col-sm-2">
        @Html.HiddenFor(model => model.q_id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        @Html.EditorFor(model => model.q_no, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
    </td>
    <td class="col-sm-6">
        @Html.EditorFor(model => model.q_question, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
    </td>
    <td class="col-sm-4">
        @if (Model.q_id == 0)
        {
            <a href="#" onclick="RemoveItem(this)">Delete</a>
        }
        else
        {
            <a class="editquest" data-id="@Model.q_id" href="#">Edit</a>
        }
    </td>
</tr>


<script type="text/javascript">
    $(".editquest").click(function () {
            $.ajax({
            url: '@Url.Action("EditQue","QMS")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $("#qmodtitle").html("Edit new Question")
                $("#qmodbody").html(result);
                $("#qmod").modal("show")
            },
            error: function (err) {
                alert(err);
            }
        });

        });
</script>

QMS.Presentation/Views/QMS/_Edit.cshtml
@model QMS.ViewModel.QHeadViewModel


@using (Html.BeginForm("Edit", "QMS", FormMethod.Post, new { id = "edit-form", name = "edit-form" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-group">
            @Html.HiddenFor(model => model.q_id, new { htmlAttributes = new { @class = "form-control id" } })
            @Html.LabelFor(model => model.q_code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.q_code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.q_code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.q_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.q_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.q_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.q_type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    List<SelectListItem> listItems = new List<SelectListItem>();
                    if (Model.q_type == "Personality")
                    {
                        listItems.Add(new SelectListItem
                        {
                            Text = "Technical",
                            Value = "Technical"
                        });
                        listItems.Add(new SelectListItem
                        {
                            Text = "Personality",
                            Value = "Personality",
                            Selected = true
                        });
                    }
                    else
                    {
                        listItems.Add(new SelectListItem
                        {
                            Text = "Technical",
                            Value = "Technical",
                             Selected = true
                        });
                        listItems.Add(new SelectListItem
                        {
                            Text = "Personality",
                            Value = "Personality"
                           
                        });
                    }

                }
                @Html.DropDownListFor(model => model.q_type, listItems, "-- Type --", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.q_type, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Close" class="btn btn-default" data-dismiss="modal" />
                <input id="btn-edit" type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    <br />
    <button type="button" id="btn-new-q" class="btn btn-warning btn-new" href="#qmod">Add Point</button>
    <br />
    <hr />
    <div id="question-list1"></div>

}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    $(document).ready(function () {
            GetList();
        });

        function GetList(){
            $.ajax({
                url: '@Url.Action("Detail","QMS")',
                type: 'get',
                data: {id: $("#q_id").val()},
                success: function (result) {
                    $("#question-list1").html(result);
                },
                error: function (err) {
                    $("#question-list1").html(err);
                }
            });
        }

        $("#edit-form").submit(function () {
            //alert($(this).serialize());
            var qList = [];
            $(this).find("#question-list").find("tr").each(function () {
                var list = { q_id: $(this).find("input[name=q_id]").val(), q_no: $(this).find("input[name=q_no]").val(), q_question: $(this).find("input[name=q_question]").val() }
                qList.push(list);
            });
            var data = {
                q_id: $(this).find("#q_id").val(),
                q_code: $(this).find("#q_code").val(),
                q_name: $(this).find("#q_name").val(),
                q_type: $(this).find("#q_type").val(),
                questiondetail: qList
            };
            //alert(JSON.stringify(data));



            $.ajax({
                url: '@Url.Action("Edit","QMS")',
                type: this.method,
                data: {model:data},
                success: function (result) {
                    if (result.success) {
                        alert("Data Successfully Saved !");
                        $(".modal").modal("hide");
                        GetList();
                    } else {
                        alert("Error!." + result.message)
                    }
                }
            });
            return false;
        });

    $('#btn-new-q').click(function () {
            $.ajax({
                url: '@Url.Action("Question","QMS")',
                type: 'get',
                success: function (result) {
                    $("#qmodtitle").html("Create new Question")
                    $("#qmodbody").html(result);
                    $("#qmod").modal("show")

                },
                error: function (err) {
                    alert(err);
                }
            });
    });

    function RemoveItem(obj) {
        var tr = $(obj).closest("tr");
        tr.remove();
    }
</script>

QMS.Presentation/Views/QMS/_List.cshtml
@model IEnumerable<QMS.ViewModel.QHeadViewModel>

<button id="btn-new-version" type="button" class="btn btn-primary btn-new">
    Create
</button>
<br />
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.q_code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.q_name)
        </th>
        <th>#</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.q_code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.q_name)
        </td>
        <td>
            <a href="#" class="view-link" data-id="@item.q_id">View</a>
        </td>
    </tr>
}

</table>

<script type="text/javascript">
    $('#btn-new-version').click(function () {
            $.ajax({
                url: '@Url.Action("Create","QMS")',
                type: 'get',
                success: function (result) {
                    $("#mvertitle").html("Create new Version")
                    $("#mverbody").html(result);
                    $("#mver").modal("show")
                },
                error: function (err) {
                    alert(err);
                }
              });
    });

    $(".view-link").click(function () {
            $.ajax({
                url: '@Url.Action("Edit", "QMS")',
                type: 'get',
                data: { id: $(this).attr("data-id") },
                success: function (result) {
                    $("#mvertitle").html("View Question");
                    $("#mverbody").html(result);
                    $("#mver").modal("show");
                }
            })

        });
</script>

QMS.Presentation/Views/QMS/_Question.cshtml
@model QMS.ViewModel.QDetailViewModel

@using (Html.BeginForm("DetailItem", "QMS", FormMethod.Post, new { id ="q-form", name = "q-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.q_no, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.q_no, new { htmlAttributes = new { @class = "form-control", @id="inputno" } })
                @Html.ValidationMessageFor(model => model.q_no, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.q_question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" >
                @Html.EditorFor(model => model.q_question, new { htmlAttributes = new { @class = "form-control question", @id = "inputques" } })
                @Html.ValidationMessageFor(model => model.q_question, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="submitq" type="submit" value="Create" class="btn btn-default" data-dismiss="modal"/>
            </div>
        </div>
    </div>
}


<script type="text/javascript">
    $("#submitq").click(function () {
        var data = { q_no : $("#inputno").val(), q_question: $("#inputques").val() };
        //alert(JSON.stringify(data))
            $.ajax({
                url: '@Url.Action("Detailitem","QMS")',
                type: 'post',
                data: { model : data },
                success: function (result) {
                    $("#question-list").append(result);
                }
        });
    });
</script>

QMS.Presentation/Views/QMS/_QuestionEdit.cshtml
@model QMS.ViewModel.QDetailViewModel

@using (Html.BeginForm("EditQue", "QMS", FormMethod.Post, new { id = "delete-form", name = "delete-form" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(model => model.q_id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.q_id, new { htmlAttributes = new { @class = "form-control", @id = "inputid", @readonly = "true" } })
            @Html.ValidationMessageFor(model => model.q_no, "", new { @class = "text-danger" })
        </div>
    </div>

    
    <div class="form-group">
        @Html.LabelFor(model => model.q_no, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.q_no, new { htmlAttributes = new { @class = "form-control", @id = "inputno" } })
            @Html.ValidationMessageFor(model => model.q_no, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.q_question, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.q_question, new { htmlAttributes = new { @class = "form-control question", @id = "inputques" } })
            @Html.ValidationMessageFor(model => model.q_question, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input id="submitq" type="submit" value="Done" class="btn btn-default" data-dismiss="modal" />
        </div>
    </div>
</div>
}


<script type="text/javascript">
    $("#submitq").click(function () {
        var data = { q_id: $("#inputid").val(), q_no : $("#inputno").val(), q_question: $("#inputques").val() };
        //alert(JSON.stringify(data))
            $.ajax({
                url: '@Url.Action("EditQue","QMS")',
                type: 'post',
                data: { model : data },
                success: function (result) {
                    GetList();
                }
        });
    });
</script>

QMS.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>